version: "3.3"

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - bean_network

  db:
    image: "postgres"
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bean
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - bean_network

  web:
    build: .
    entrypoint: /src/entrypoint.sh
    environment:
      - DEBUG=1
      - IS_SERVER_DB=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - DATABASE_HOST=db
      - DATABASE_NAME=salesforce
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root123
      - DATABASE_PORT=5432
      - DJANGO_CONFIGURATION=Local
      - DJANGO_SETTINGS_MODULE=config.local
      - REDIRECT_URI=https://outlook-sf.tpptechnology.com
    volumes:
      - .:/src
    ports:
      - "80:8000"
    networks:
      - bean_network
      - host
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A config worker -B -l info
    environment:
      - DEBUG=1
      - IS_SERVER_DB=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - DATABASE_HOST=db
      - DATABASE_NAME=salesforce
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root123
      - DATABASE_PORT=5432
      - DJANGO_CONFIGURATION=Local
      - DJANGO_SETTINGS_MODULE=config.local
      - REDIRECT_URI=https://outlook-sf.tpptechnology.com
    networks:
      - bean_network
      - host
    depends_on:
      - web
      - db

networks:
  bean_network:
    driver: bridge
  host:
