# Generated by Django 4.2.6 on 2023-10-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=25, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=25, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('short_token', models.TextField()),
                ('token', models.TextField()),
                ('expires_in', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='Apps.service')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=25, unique=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_relations', to='Apps.friend', to_field='uid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='Apps.user', to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='Apps.conversation', to_field='uid')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_messages', to='Apps.relation', to_field='uid')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_friends', to='Apps.service'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['uid'], name='Apps_conver_uid_d6ab63_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uid'], name='Apps_user_uid_5985a5_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['uid'], name='Apps_relati_uid_d34248_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['uid'], name='Apps_messag_uid_273c21_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['uid'], name='Apps_friend_uid_a6ba80_idx'),
        ),
    ]
