# Generated by Django 4.2.6 on 2023-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_migration_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.IntegerField(choices=[(1, 'USER'), (2, 'GROUP'), (3, 'PAGE')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('User', 'User'), ('Page', 'Page')], default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
